config/routes.rb
Rails.application.routes.draw do
  
  root 'static_pages#home'
  get   '/signup',  to: 'users#new'
  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get   '/edit-basic-info/:id', to: 'users#edit_basic_info', as: :basic_info
  patch 'update-basic-info',    to: 'users#update_basic_info'
  get   'users/:id/attendances/:date/edit',   to: 'attendances#edit',   as: :edit_attendances
  patch 'users/:id/attendances/:date/update', to: 'attendances#update', as: :update_attendances

  resources :users do
    resources :attendances, only: :create
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :attendances, dependent: :destroy
  
  # 「remember_token」という仮想の属性を作成します。
  attr_accessor :remember_token

  before_save {self.email = email.downcase }
  validates :name, presence: true,  length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 100 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
                                # 大文字と小文字の区別を無視する
  validates :basic_time, presence: true
  validates :work_time,  presence: true                              
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  validates :department, length: { in: 3..50 }, allow_blank: true

  def self.search(search) #ここでのself.はUser.を意味する
    if search
      where(['name LIKE ?', "%#{search}%"]) #検索とnameの部分一致を表示。User.は省略
    else
      all #全て表示。User.は省略
    end
  end
  
  # 渡された文字列のハッシュ値を返します。
  def User.digest(string)
    cost = 
      if ActiveModel::SecurePassword.min_cost
        BCrypt::Engine::MIN_COST
      else
        BCrypt::Engine.cost
      end
    BCrypt::Password.create(string, cost: cost)
  end

  # ランダムなトークンを返します。
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  # 永続セッションのためハッシュ化したトークンをデータベースに記憶します。
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  # トークンがダイジェストと一致すればtrueを返します。
  def authenticated?(remember_token)
    # ダイジェストが存在しない場合はfalseを返して終了します。
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user,       only: [:show, :edit, :update, :destroy, :edit_basic_info, :update_basic_info]
  before_action :logged_in_user, only: [:index, :show, :edit, :update, :destroy, :edit_basic_info, :update_basic_info]
  before_action :admin_user,     only: [:index, :destroy, :edit_basic_info, :update_basic_info]
  before_action :admin_or_correct_user, only: [:show, :edit, :update]

  def index
    if params[:search].present?
      @users = User.paginate(page: params[:page]).search(params[:search])
    else
      @users = User.paginate(page: params[:page])
    end
  end
  
  def show
    @first_day = first_day(params[:first_day])
    @last_day = @first_day.end_of_month
    (@first_day..@last_day).each do |day|
      unless @user.attendances.any? {|attendance| attendance.worked_on == day}
       record = @user.attendances.build(worked_on: day)
       record.save
      end
    end
    @dates = user_attendances_month_date
    @worked_sum = @dates.where.not(started_at: nil).count
  end

  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "ユーザーの新規作成に成功しました。"
      redirect_to @user # redirect_to user_url(@user)
    else
      render 'new'
    end
  end
  
  def edit
  end
  
  def update
    if @user.update_attributes(user_params)
      flash[:success] = "ユーザー情報を更新しました。"
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  def destroy
    @user.destroy
    flash[:success] = "#{@user.name}のデータを削除しました。"
    redirect_to users_url
  end
  
  def edit_basic_info
  end
  
  def update_basic_info
    @users = User.all
    ActiveRecord::Base.transaction do # トランザクションを開始します。
      @users.each do |user|
        user.update_attributes!(basic_info_params)
      end
    end
    flash[:success] = "全ユーザーの基本情報を更新しました。"
    redirect_to users_url
  rescue ActiveRecord::RecordInvalid # トランザクションによるエラーの分岐です。
    flash[:danger] = "基本情報の更新に失敗しました。<br>" + @user.errors.full_messages.join("<br>")
    render 'edit_basic_info'
  end  
    

  private
  
    def user_params
      params.require(:user).permit(:name, :email, :department, 
                                   :password,:password_confirmation)
    end
    
    def basic_info_params
      params.require(:user).permit(:basic_time, :work_time)
    end

end

app/helpers/users_helper.rb
module UsersHelper
  # 基本時間などの値を、指定の書式にフォーマットして返す
  def format_basic_time(datetime)
    format("%.2f", ((datetime.hour * 60) + datetime.min)/60.0)
  end
end

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |f| %>
  <%= render 'shared/error_messages', object: @user%>
    
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>
  
  <%= f.label :department %>
  <%= f.text_field :department, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>
      
  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "削除", user, method: :delete,
                         data: { confirm: "削除してよろしいですか？" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "設定") %>
<% provide(:button_text, '更新する') %>
<h1>アカウント情報の更新</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
  　<%= render 'form' %>
  </div>
</div>

app/views/users/edit_basic_info.html.erb
<% provide(:title, "基本情報編集") %>

<h1>基本情報の編集</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @user, url: update_basic_info_path(params: {id: @user.id}), local: true) do |f| %>
      <%= render 'shared/error_messages', object: @user %>

      <%= f.label :basic_time %>
      <%= f.time_field :basic_time, class: 'form-control' %>

      <%= f.label :work_time %>
      <%= f.time_field :work_time, class: 'form-control' %>

      <%= f.submit "更新する", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, '一覧') %>

<!-- 追加機能 no.9 -->
<% if params[:search].present? %>
  <h1>検索結果</h1>
<% else %>
  <h1>ユーザー一覧</h1>
<% end %>

<!--  検索拡張機能  -->
<div id="nav-search">
  <%= form_tag(users_path, :method => 'get') do %>
    <div class="input-group">
      <%= text_field_tag :search, params[:search], placeholder: "ユーザー名検索", class: "form-control" %>
      <span class="input-group-btn">
      <%= button_tag "検索", :name => nil, class: "btn btn-primary" %>
      </span>
    </div>
  <% end %>
</div>

<%= will_paginate @users, :previous_label => ' &lt 前へ', :next_label => '次へ &gt' %>

<ul class="users">
    <%= render @users %>
</ul>

<%= will_paginate @users, :previous_label => ' &lt 前へ', :next_label => '次へ &gt'%>

app/views/users/new.html.erb
<% provide(:title, 'ユーザー作成') %>
<% provide(:button_text, '作成する') %>
<h1>ユーザー新規作成</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, '勤怠表示') %>
<div>
  <table class="table-bordered table-condensed">
    <tr>
      <td>
        <%= link_to "←", user_path(params: {id: @user.id, first_day: @first_day.prev_month }),
                         class: "btn btn-xs btn-primary" %>
        &emsp;<%= @first_day.to_s(:year_month) %>　時間管理表&emsp;
        <%= link_to "→", user_path(params: {id: @user.id, first_day: @first_day.next_month }),
                         class: "btn btn-xs btn-primary" %>
      </td>
      <td>指定勤務時間　<%= format_basic_time(@user.work_time) %></td>
      <td colspan="3">基本時間　<%= format_basic_time(@user.basic_time) %></td>
      <td>初日　<%= @first_day.to_s(:date) %></td>
    </tr>

    <tr>
      <td>所属：<%= @user.department.present? ? @user.department : "未設定" %></td>
      <td>氏名：<%= @user.name %></td>
      <td>コード</td>
      <td></td>
      <td>出勤日数：<%= @worked_sum %>日</td>
      <td>締日　<%= @last_day.to_s(:date) %></td>
    </tr>
  </table>
  <%= link_to "勤怠を編集", edit_attendances_path(@user, @first_day), class: "btn btn-primary btn-edit" %>
<!--↓↓↓ここから先が今回記述するコード↓↓↓-->
  <table class = "table-bordered table-striped table-condensed">
    <thead>
      <tr> <!--rowspan:縦結合、colspan：横結合-->
        <th rowspan = "2">日付</th>
        <th rowspan = "2">曜日</th>
        <th colspan = "3">出社</th>
        <th colspan = "3">退社</th>
        <th rowspan = "2">在社時間</th>
        <th rowspan = "2">備考</th>
      </tr>
      <tr>
        <th>時</th>
        <th>分</th>
        <th></th>
        <th>時</th>
        <th>分</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @dates.each do |day| %>
        <tr>
          <td><%= day.worked_on.to_s(:date) %></td>
          <td>
            <% if day.worked_on.wday == 0 %>
              <font color="red">日</font>
            <% elsif day.worked_on.wday == 6 %>
              <font color="blue">土</font>
            <% else %>
              <%= $days_of_the_week[day.worked_on.wday] %>
            <% end %>
          </td>
          <td><%= day.started_at.to_s(:hour) if day.started_at.present? %></td>
          <td><%= day.started_at.floor_to(15.minutes).to_s(:min) if day.started_at.present? %></td>
          <td>
            <% if (day.worked_on == Date.current) && day.started_at.nil? %>
              <%= button_to "出社", user_attendances_path(@user), class: "btn btn-xs btn-primary" %>
            <% end %>
          </td>
          <td><%= day.finished_at.to_s(:hour) if day.finished_at.present? %></td>
          <td><%= day.finished_at.floor_to(15.minutes).to_s(:min) if day.finished_at.present? %></td>
          <td>
            <% if (day.worked_on == Date.current) && day.started_at.present? && day.finished_at.nil? %>
              <%= button_to "退社", user_attendances_path(@user), class: "btn btn-xs btn-primary" %>
            <% end %>
          </td>
          <td>
            <% if day.started_at.present? && day.finished_at.present? %>
              <%= working_times(day.started_at, day.finished_at) %>
              <% seconds = (day.finished_at.floor_to(15.minutes) - day.started_at.floor_to(15.minutes)).to_i %>
              <% @total_seconds = @total_seconds.to_i + seconds %>
            <% end %>
          </td>
          <td><%= day.note %></td>
        </tr>
      <% end %>
    </tbody>
    <tfoot>
      <tr>
        <td colspan = "2"></td>
        <td colspan = "6">総合勤務時間：<%= format_basic_time(@user.basic_time).to_f * @worked_sum %></td>
        <td>在社合計：<%= working_times_sum(@total_seconds) unless @total_seconds.nil? %></td>
        <td></td>
      </tr>
    </tfoot>
  </table>
</div>