config/routes.rb
Rails.application.routes.draw do
  
  root 'static_pages#home'
  get   '/signup',  to: 'users#new'
  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get   '/edit-basic-info/:id', to: 'users#edit_basic_info', as: :basic_info
  patch 'update-basic-info',    to: 'users#update_basic_info'
  get   'users/:id/attendances/:date/edit',   to: 'attendances#edit',   as: :edit_attendances
  patch 'users/:id/attendances/:date/update', to: 'attendances#update', as: :update_attendances

  resources :users do
    resources :attendances, only: :create
  end
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  
  validates :worked_on, presence: true
  validates :note, length: { maximum: 50 }

  validate :finished_at_is_invalid_without_a_started_at
  validate :finished_at_must_be_later_than_started_at

  def finished_at_is_invalid_without_a_started_at
      errors.add(:started_at, "が必要です") if started_at.blank? && finished_at.present?
  end
  
  # 追加機能7
  def finished_at_must_be_later_than_started_at
    if started_at.present? && finished_at.present?
      errors.add(:finished_at, "が出勤時間よりも早いため登録できません") if started_at > finished_at
    end
  end
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :set_user, only: [:edit, :update]
  before_action :set_user_from_attendance, only: [:create]
  before_action :logged_in_user, only: [:create, :update, :edit]
  before_action :admin_or_correct_user, only: [:create, :update, :edit]

  def create
    # @user = User.find(params[:user_id])
    @attendance = @user.attendances.find_by(worked_on: Date.today)
    if @attendance.started_at.nil?
      @attendance.update_attributes(started_at: current_time)
      flash[:info] = 'おはようございます。'
    elsif @attendance.finished_at.nil?
      @attendance.update_attributes(finished_at: current_time)
      flash[:info] = 'おつかれさまでした。'
    else
      flash[:danger] = 'トラブルがあり、登録出来ませんでした。'
    end
    redirect_to(@user)
  end
  
  def edit
    @first_day = Date.parse(params[:date])
    @last_day = @first_day.end_of_month
    @dates = @user.attendances.where('worked_on >= ? and worked_on <= ?', @first_day, @last_day).order('worked_on')
  end
  
  def update
    if attendances_invalid?
      attendances_params.each do |id, item|
      attendance = Attendance.find(id)
      attendance.update_attributes!(item)
    end
      flash[:success] = '勤怠情報を更新しました。'
      redirect_to user_url(@user, params:{first_day: params[:date]})
    else
      flash[:danger] = "不正な時間入力がありました、再入力してください。"
      redirect_to edit_attendances_path(@user, params[:date])
    end
  end

  private
    def attendances_params
      params.permit(attendances: [:started_at, :finished_at, :note])[:attendances]
    end
    
    def set_user_from_attendance
      @user = User.find(params[:user_id])
    end

end

app/helpers/attendances_helper.rb
module AttendancesHelper
  def current_time
    Time.new(
      Time.now.year,
      Time.now.month,
      Time.now.day,
      Time.now.hour,
      Time.now.min, 0
    )
  end
  
  # 追加機能no.10に合わせた表示
  def working_times(started_at, finished_at)
    format("%.2f", (((finished_at.floor_to(15.minutes) - started_at.floor_to(15.minutes)) / 60) / 60.0).floor_to(0.25))
  end
  
  def working_times_sum(seconds)
    format("%.2f", (seconds / 60 / 60.0).floor_to(0.25))
  end
  
  def first_day(date)
    !date.nil? ? Date.parse(date) : Date.current.beginning_of_month
  end

  def user_attendances_month_date
    @user.attendances.where('worked_on >= ? and worked_on <= ?', @first_day, @last_day).order('worked_on')
  end
  
  def attendances_invalid?
    attendances = true
    attendances_params.each do |id, item|
      if item[:started_at].blank? && item[:finished_at].blank?
        next
      elsif item[:started_at].blank? || item[:finished_at].blank?
        attendances = false
        break
      elsif item[:started_at] > item[:finished_at]
        attendances = false
        break
      end
    end
    return attendances
  end
end

app/views/attendances/edit.html.erb
<% provide(:title,"勤怠編集" ) %>
<div>
  <h1>勤怠編集画面</h1>
  <%= form_with(model: @user, url: update_attendances_path, local: true, method: :patch) do |f| %>
    <table class = "table-bordered table-striped table-condensed">
      <thead>
        <tr>
          <th>日付</th>
          <th>曜日</th>
          <th>出社</th>
          <th>退社</th>
          <th>在社時間</th>
          <th>備考</th>
        </tr>
      </thead>
      <tbody>
        <% @dates.each do |day| %>
          <%= fields_for "attendances[]", day do |af| %>
            <tr>
              <td><%= day.worked_on.to_s(:date) %></td>
              <td>
              <% if day.worked_on.wday == 0 %>
                <font color="red">日</font>
              <% elsif day.worked_on.wday == 6 %>
                  <font color="blue">土</font>
              <% else %>
                <%= $days_of_the_week[day.worked_on.wday] %>
              <% end %>
              </td>
              <% if Date.current < day.worked_on %>
                <td><%= af.time_field :started_at, readonly: true, class: "form-control" %></td>
                <td><%= af.time_field :finished_at, readonly: true, class: "form-control" %></td>
              <% else %>
                <td><%= af.time_field :started_at, class: "form-control" %></td>
                <td><%= af.time_field :finished_at, class: "form-control" %></td>
              <% end %>
                <td><% if day.started_at.present? && day.finished_at.present? %>
                    <%= working_times(day.started_at, day.finished_at) %>
                  <% end %>
              </td>
              <td><%= af.text_field :note, class: "form-control" %></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
    <div class="btn-attendances-update">
      <%= f.submit "更新", class: "btn btn-primary btn-update" %>
      <%= link_to "キャンセル", user_path(@user, params:{first_day: @first_day }), class: "btn btn-default btn-block btn-update" %>
    </div>
  <% end %>
</div>